apiVersion: apps/v1
kind: Deployment

metadata:
  name: server-production
  labels:
    app: server-production
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-production
  template:
    metadata:
      name: server-production
      labels:
        app: server-production
    spec:
      restartPolicy: Always
      containers:
        - name: server-production
          image: registry.gitlab.com/medhir/blog/master/server:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: creds
              mountPath: "etc/creds"
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/creds/storage-credentials.json"
            - name: ENVIRONMENT
              value: "production"
            - name: CLOUDFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: apikey
            - name: CLOUDFLARE_API_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: email
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-server-client
                  key: client-id
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-server-client
                  key: client-secret
            - name: KEYCLOAK_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-medhir-com-admin
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-medhir-com-admin
                  key: password
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb
                  key: api-key
            - name: HONEYCOMB_DATASET
              value: production
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: medhir-com-database
                  key: host
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: medhir-com-database
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: medhir-com-database
                  key: password
      volumes:
        - name: creds
          secret:
            secretName: api-server-storage-credentials
            items:
              - key: storage-credentials.json
                path: storage-credentials.json
      imagePullSecrets:
        - name: regcred