apiVersion: apps/v1
kind: Deployment

metadata:
  name: server-review
  labels:
    app: server-review
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-review
  template:
    metadata:
      name: server-review
      labels:
        app: server-review
    spec:
      restartPolicy: Always
      containers:
        - name: server-review
          image: registry.gitlab.com/medhir/blog/master/server:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: creds
              mountPath: "etc/creds"
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/creds/storage-credentials.json"
            - name: ENVIRONMENT
              value: "review"
            - name: CLOUDFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: apikey
            - name: CLOUDFLARE_API_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: email
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-server-client
                  key: client-id
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-server-client
                  key: client-secret
      volumes:
        - name: creds
          secret:
            secretName: api-server-storage-credentials
            items:
              - key: storage-credentials.json
                path: storage-credentials.json
      imagePullSecrets:
        - name: regcred