services:
  db:
    image: postgres
    volumes:
      - ./server/controllers/storage/sql/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=keycloak
  keycloak:
    image: keycloak/keycloak
    volumes:
      - keycloak:/opt/keycloak/data/
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=docker
    ports:
      - "8080:8080"
    depends_on:
      - db
  server:
   build:
     context: ./server
     dockerfile: Dockerfile.dev
   ports:
     - "9000:9000"
   volumes:
     - ./server:/server
   secrets:
     - github_token
   depends_on:
     - db
     - keycloak
   env_file:
     - ./server/.env
   networks:
    default:
      aliases:
        - medhir
  www:
   container_name: www
   build:
     context: ./www
     dockerfile: Dockerfile.dev
   volumes:
     - ./www:/www
   ports:
     - "3000:3000"
   depends_on:
     - server
volumes:
  pgdata:
  keycloak:
networks:
  default:
secrets:
  github_token:
    file: ./secrets/github_token.txt