// Code generated by mockery v1.0.0. DO NOT EDIT.

package handlers

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// MockHandlers is an autogenerated mock type for the Handlers type
type MockHandlers struct {
	mock.Mock
}

// GetPhotos provides a mock function with given fields:
func (_m *MockHandlers) GetPhotos() http.HandlerFunc {
	ret := _m.Called()

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func() http.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// Login provides a mock function with given fields:
func (_m *MockHandlers) Login() http.HandlerFunc {
	ret := _m.Called()

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func() http.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// ValidateJWT provides a mock function with given fields:
func (_m *MockHandlers) ValidateJWT() http.HandlerFunc {
	ret := _m.Called()

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func() http.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}
