apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  selector:
    app: gitlab
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 6000
    - port: 443
      name: https
      protocol: TCP
      targetPort: 6001
    - port: 22
      name: ssl
      protocol: TCP
      targetPort: 6002