apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-server-datadir
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
status: {}
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-server-logs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
status: {}