FROM golang:1.22-alpine
ENV GO111MODULE=on
WORKDIR /server
RUN apk add git
RUN --mount=type=secret,id=GITHUB_TOKEN \
    git config --global url."https://$(cat /run/secrets/GITHUB_TOKEN):x-oauth-basic@github.com/".insteadOf "https://github.com/"
RUN go install github.com/cosmtrek/air@latest
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
CMD ["air", "-c", ".air.toml"]