FROM golang:1.22-alpine
ENV GO111MODULE=on
WORKDIR /server
RUN apk add git
RUN git config --global url."https://${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}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
RUN go install github.com/air-verse/air@latest
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
CMD ["air", "-c", ".air.toml"]