FROM node:current-alpine3.18 AS builder
WORKDIR /www
COPY package.json yarn.lock ./
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
RUN yarn install
COPY . .
ARG ENV=test
RUN yarn build:$ENV
EXPOSE 3000
ENTRYPOINT NODE_ENV=test yarn test