// Code generated by mockery v1.1.1. DO NOT EDIT.

package dns

import mock "github.com/stretchr/testify/mock"

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

// AddCNAMERecord provides a mock function with given fields: name
func (_m *MockManager) AddCNAMERecord(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCNAMERecord provides a mock function with given fields: name
func (_m *MockManager) DeleteCNAMERecord(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
