// Code generated by mockery v1.0.0. DO NOT EDIT.

package auth

import mock "github.com/stretchr/testify/mock"

// MockAuth is an autogenerated mock type for the Auth type
type MockAuth struct {
	mock.Mock
}

// Login provides a mock function with given fields: request
func (_m *MockAuth) Login(request *LoginRequest) (*LoginResponse, error) {
	ret := _m.Called(request)

	var r0 *LoginResponse
	if rf, ok := ret.Get(0).(func(*LoginRequest) *LoginResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LoginResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*LoginRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Validate provides a mock function with given fields: jwt
func (_m *MockAuth) Validate(jwt string) error {
	ret := _m.Called(jwt)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(jwt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
