apiVersion: apps/v1
kind: Deployment

metadata:
  name: blog
  labels:
    app: blog
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      name: blog
      labels:
        app: blog
    spec:
      restartPolicy: Always
      containers:
        - name: blog
          image: gcr.io/blog-121419/blog:kube-test-3
          ports:
            - containerPort: 9000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-storage
                  key: access-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-storage
                  key: access-secret
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  selector:
    app: blog
  ports:
    - port: 9000
