apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - medhir.com
        - authdev.medhir.com
        - staging.medhir.com
      secretName: medhir-blog-prod-cert
  rules:
    - host: medhir.com
      http:
        paths:
          - path: /
            backend:
              serviceName: blog-service
              servicePort: 9000
    - host: authdev.medhir.com
      http:
        paths:
          - path: /
            backend:
              serviceName: fusionauth
              servicePort: 9011
