apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: dev.medhir.com
      http:
        paths:
          - path: /
            backend:
              serviceName: blog-service
              servicePort: 9000
