apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - dev.medhir.com
      secretName: medhir-cert
  rules:
    - host: dev.medhir.com
      http:
        paths:
          - path: /
            backend:
              serviceName: blog-service
              servicePort: 9000
