// Code generated by mockery v1.0.0. DO NOT EDIT.

package imageprocessor

import mock "github.com/stretchr/testify/mock"

// MockImageProcessor is an autogenerated mock type for the ImageProcessor type
type MockImageProcessor struct {
	mock.Mock
}

// ProcessImage provides a mock function with given fields: buf
func (_m *MockImageProcessor) ProcessImage(buf []byte) ([]byte, error) {
	ret := _m.Called(buf)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(buf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(buf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
