// Code generated by mockery v1.1.1. DO NOT EDIT.

package blog

import mock "github.com/stretchr/testify/mock"

// MockBlog is an autogenerated mock type for the Blog type
type MockBlog struct {
	mock.Mock
}

// AddDraft provides a mock function with given fields: title, markdown
func (_m *MockBlog) AddDraft(title string, markdown string) error {
	ret := _m.Called(title, markdown)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(title, markdown)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDraft provides a mock function with given fields: id
func (_m *MockBlog) GetDraft(id string) ([]byte, error) {
	ret := _m.Called(id)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDrafts provides a mock function with given fields:
func (_m *MockBlog) GetDrafts() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPost provides a mock function with given fields: id
func (_m *MockBlog) GetPost(id string) ([]byte, error) {
	ret := _m.Called(id)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPosts provides a mock function with given fields:
func (_m *MockBlog) GetPosts() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDraft provides a mock function with given fields: id, title, markdown
func (_m *MockBlog) UpdateDraft(id string, title string, markdown string) error {
	ret := _m.Called(id, title, markdown)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(id, title, markdown)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
